name: LEI-RDF

on:
  push:
    branches: [ standalone ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java 1.8
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8

    - name: Compile transform
      run: |
        cd tools
        mvn install -B --no-transfer-progress
        cd ..

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build container
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/pulquero/lei-rdf:latest
